services:
  traefik:
    image: traefik:v2.5
    restart: always
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      # - "--providers.docker.exposedbydefault=false"
      - "--api.dashboard=true"
      # - "--log.level=DEBUG"
      # Enable Prometheus metrics endpoint
      # - "--entrypoints.metrics.address=:9091"
      # - "--metrics.prometheus=true"
      # - "--metrics.prometheus.entrypoint=metrics"
    labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.api.rule=(Host(`host.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`)))"
      - "traefik.http.routers.api.rule=((PathPrefix(`/api`) || PathPrefix(`/dashboard`)))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=toe:$$apr1$$9dmswe8v$$k1RQ.WAI57gWWHD.l/.dV1,sml:$$apr1$$ia38r5sb$$8uxrh4fGN.OOFjdhB9FNW0"
      # - "traefik.http.middlewares.auth.basicauth.removeheader=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080
      # - 9091:9091 # Prometheus metrics endpoint
    networks: ["sml_service_network"]
networks:
  sml_service_network:
    name: sml_service_network
    external: true
